#!/bin/bash

set -euxoH pipefail
source /root/.bashrc > /dev/null 2>&1

cd /root
rm -rf ${DEMO_HOME:?}
cp -R ${SOLUTIONS_DIR:?}/06-use-crd-data-in-your-controller ${DEMO_HOME:?}

cd ${DEMO_HOME:?}
make install
kubectl delete websites.kubecon.my.domain website-sample || true
sleep 2 # Can't use wait since it is a field change (crd is already established) and jsonpath not implemented in this version
kubectl apply --filename config/samples/kubecon_v1beta1_website-with-image-tag.yaml