#! /bin/bash

set -euxoH pipefail

source /root/.bashrc > /dev/null 2>&1

# Install docker
dpkg -i ${SOLUTIONS_DIR:?}/track/docker-ce-cli_20.10.14~3-0~ubuntu-hirsute_amd64.deb 
dpkg -i ${SOLUTIONS_DIR:?}/track/containerd.io_1.4.13-1_amd64.deb 
dpkg -i ${SOLUTIONS_DIR:?}/track/docker-ce_20.10.14~3-0~ubuntu-hirsute_amd64.deb 

echo '
resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
  patch: |-   
    - op: replace
      path: "/spec/template/spec/containers/0/imagePullPolicy"
      value: IfNotPresent
' > ${DEMO_HOME:?}/config/manager/kustomization.yaml