#! /bin/bash

set -euxoH pipefail

# Install docker
wget https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/containerd.io_1.4.13-1_amd64.deb
wget https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-ce-cli_20.10.14~3-0~ubuntu-hirsute_amd64.deb
wget https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-ce_20.10.14~3-0~ubuntu-hirsute_amd64.deb

dpkg -i docker-ce-cli_20.10.14~3-0~ubuntu-hirsute_amd64.deb 
dpkg -i containerd.io_1.4.13-1_amd64.deb 
dpkg -i docker-ce_20.10.14~3-0~ubuntu-hirsute_amd64.deb 

echo '
resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
  patch: |-   
    - op: replace
      path: "/spec/template/spec/containers/0/imagePullPolicy"
      value: Always
' > ${DEMO_HOME:?}/config/manager/kustomization.yaml