#!/bin/bash

set -euxoH pipefail
source /root/.bashrc > /dev/null 2>&1

cd /root
rm -rf ${DEMO_HOME:?}
cp -R /root/kubecon-instruqt-solutions/06-use-crd-data-in-your-controller ${DEMO_HOME:?}

cd ${DEMO_HOME:?}
make install
kubectl delete websites.kubecon.my.domain website-sample
kubectl apply --filename config/samples/kubecon_v1beta1_website-with-image-tag.yaml