#!/bin/bash

source /root/.bashrc > /dev/null 2>&1

echo '
// Create a service with the correct field values. By creating this in a function,
// it can be reused by all lifecycle functions (create, update, delete).
func newService(name, namespace string) *corev1.Service {
  return &corev1.Service{
    ObjectMeta: metav1.ObjectMeta{
      Name:      name,
      Namespace: namespace,
      Labels:    setResourceLabels(name),
    },
    Spec: corev1.ServiceSpec{
      Ports: []corev1.ServicePort{
        {
          Port:     80,
          NodePort: 31000,
        },
      },
      Selector: setResourceLabels(name),
      Type:     corev1.ServiceTypeNodePort,
    },
  }
}
' >> ${DEMO_HOME:?}/controllers/website_controller.go
