#!/bin/bash

source /root/.bashrc > /dev/null 2>&1

echo '
// Define and then create a service for your Website resource
func (r *WebsiteReconciler) createService(ctx context.Context, customResource *kubeconv1beta1.Website) error {
	labels := map[string]string{
		"website": customResource.Name,
		"type": customResource.Kind,
	}

	service := &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      customResource.Spec.Name,
			Namespace: customResource.Namespace,
			Labels:    labels,
		},
		Spec: corev1.ServiceSpec{
			Ports: []corev1.ServicePort{
				{
					Port:     80,
					NodePort: 31000,
				},
			},
			Selector: labels,
			Type:     corev1.ServiceTypeNodePort,
		},
	}

	return r.Client.Create(ctx, service)
}
' >> ${DEMO_HOME:?}/controllers/website_controller.go
