#!/bin/bash

set -euxoH pipefail
source /root/.bashrc > /dev/null 2>&1

cd /root
rm -rf ${DEMO_HOME:?}
mv /root/kubecon-instruqt-solutions/08-view-your-website ${DEMO_HOME:?}

cd ${DEMO_HOME:?}
make install