#!/bin/bash

set -euxoH pipefail

grep "errors.IsAlreadyExists(err)" ${DEMO_HOME:?}/controllers/website_controller.go || fail-message "Have you successfully handled an 'already exists' error message?"
