#!/bin/bash

set -euxoH pipefail
source /root/.bashrc > /dev/null 2>&1

WEBSITES=$(kubectl get websites.kubecon.my.domain --output json | jq '.items | length')
[[ ${WEBSITES} -eq 1 ]] || fail-message "You should have 1 website installed in the cluster. Currently you have ${WEBSITES} installed."  
