#!/bin/sh
#
# This script runs when the platform cleanup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# CAREFUL - This same list is being used in the 07-fleetops setup-docker-vm script
names="sherlockgpt walle-learn droidgpt wakandanet haip-desk the-matrix-decoder pokenet stranger-algorithms"
names=$(echo $names)

max_retries=5
for name in $names; do
    (
        try=0
        while [ "$try" -lt "$max_retries" ]; do
            cat <<EOF | kubectl --context kind-platform apply --filename -
apiVersion: marketplace.kratix.io/v1
kind: app
metadata:
  name: ${name}
  namespace: default
spec:
  name: ${name}
  image: syntasso/sample-todo-app:v2.0.0
  dbDriver: postgresql
  service:
    port: 8080
EOF
            exit_code=$?
            if [ "$exit_code" -eq 0 ]; then
                break
            else
                try=$((try + 1))
                echo "Apply failed for ${name}, retrying kubectl apply... ($try/$max_retries)"
                sleep 2
            fi
        done
    ) &
done
wait

sleep 5
