#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

try=0
max_retries=5
until [ $try -eq $max_retries ]; do
    cat << EOF | kubectl apply --context kind-platform -f -
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  labels:
    environment: backstage
  name: backstage
spec:
  strictMatchLabels: true
  path: backstage
  stateStoreRef:
    kind: BucketStateStore
    name: default
EOF
    exit_code=$?
    if [ $exit_code -eq 0 ]; then
        break
    else
        try=$((try + 1))
        echo "Apply failed, retrying kubectl apply... ($try/$max_retries)"
        sleep 2
    fi
done

cp -r ${HOME}/resources/backstage/workflow-container ${HOME}/hackathon/app-as-a-service/internal/backstage
