#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

if [ -f "$HOME/kubecon/on-demand-force" ]; then
    # This is used to enable a force continue
    echo "Warning: By using force you may not have the setup you need for future steps"
    exit 0
fi

if ! kubectl wait --context kind-platform --timeout=5s --for=condition=complete job -l kratix.io/pipeline-name=instance-configure,kratix.io/promise-name=postgresql; then
    fail-message "Looks like you haven't requested your example Postgres yet. Please request before moving on."
    exit 1
fi

if ! kubectl wait --context kind-worker --timeout=5s --for=condition=Ready pod -l application=spilo; then
    fail-message "Looks like the example Postgres hasn't been fully installed. Try again soon and if this persists check with an instructor."
    exit 1
fi

if [ -f "$HOME/kubecon/on-demand" ] || [ -f "$HOME/kubecon/self-paced" ]; then
    exit 0
else
    fail-message "Not so fast! This course is being time managed, hang on for the speakers cue. But feel free to let them know and keep exploring!"
    exit 1
fi
