#!/usr/bin/env sh

set -eux

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"

mkdir -p /kratix/output/backstage
cat << EOF > /kratix/output/backstage/component.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-${name}
  title: "${name} App"
  description: App created via the Promise
  annotations:
    backstage.io/kubernetes-label-selector: app=${name}
  links:
  - url: https://github.com/syntasso/kratix-marketplace
    title: Support
    icon: help
spec:
  type: service
  lifecycle: production
  owner: kratix-worker
  dependsOn:
    - component:default/app
  providesApis:
    - app-promise-api
EOF

cat << EOF >> /kratix/metadata/destination-selectors.yaml
- directory: backstage
  matchLabels:
    environment: backstage
EOF
