#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

try=0
max_retries=5
until [ $try -eq $max_retries ]; do
    cat <<EOF | kubectl --context kind-platform apply --filename -
apiVersion: marketplace.kratix.io/v1
kind: app
metadata:
  name: todoer
  namespace: default
spec:
  name: todoer
  image: syntasso/sample-todo-app:v1.0.0
  dbDriver: postgresql
  service:
    port: 8080
EOF
    exit_code=$?
    if [ $exit_code -eq 0 ]; then
        break
    else
        try=$((try + 1))
        echo "Apply failed, retrying kubectl apply... ($try/$max_retries)"
        sleep 2
    fi
done

kubectl wait --context kind-platform --for=create job -l kratix.io/resource-name=todoer
kubectl wait --context kind-platform --for=condition=complete job -l kratix.io/resource-name=todoer

touch $HOME/kubecon/compose
