apiVersion: v1
data:
  config: |
    app:
      title: Scaffolded Backstage App
      baseUrl: http://localhost:31340

    organization:
      name: My Backstage

    backend:
      baseUrl: http://localhost:31340
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: http://localhost:31340
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: false
      database:
        client: better-sqlite3
        connection: ':memory:'
      auth:
        dangerouslyDisableDefaultAuthPolicy: true
    integrations:
      awsS3:
        - endpoint: 'http://minio.kratix-platform-system.svc.cluster.local'
          s3ForcePathStyle: true
          accessKeyId: ${AWS_ACCESS_KEY_ID}
          secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker' # Alternatives - 'local'
      publisher:
        type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

    auth:
      environment: development
      # see https://backstage.io/docs/auth/ to learn about auth providers
      providers:
        # See https://backstage.io/docs/auth/guest/provider
        guest:
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      providers:
        awsS3:
          kratix-minio:
            bucketName: kratix
            prefix: backstage/
            region: us-east-2
            schedule:
              frequency: { seconds: 10 }
              timeout: { seconds: 30 }
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location, Template]

      useUrlReadersSearch: true

    permission:
      # setting this to `false` will disable permissions
      enabled: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: backstage
